language: node_js
node_js:
  - 9.11
script:
  - npm run ci
after_success:
  # {{{ SSH Key の復帰
  - openssl aes-256-cbc -K $encrypted_e6cfc0b0977e_key -iv $encrypted_e6cfc0b0977e_iv -in .\/.travis\/id_rsa.enc -out ~\/.ssh/kcwidget/id_rsa -d
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\nIdentityFile ~/.ssh/kcwidget/id_rsa\n" >> ~/.ssh/config
  # }}}
  - git remote set-url origin git@github.com:otiai10/kanColleWidget.git
  - ./scripts/should_deploy.sh && npm run build && npm run pack && npm run publish
