name: Web Store TEST
on:
  schedule:
    - cron: '0 4 * * *'

jobs:
  delivery:
    runs-on: ubuntu-latest
    env:
      # v3開発版のAPP_ID
      CHROMEWEBSTORE_APP_ID: egkgleinehaapbpijnlpbllfeejjpceb
      NODE_ENV: staging
    steps:
    - uses: actions/checkout@v2
      with:
        ref: develop
        fetch-depth: 0
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install dependencies
      run: npm install

    - name: Git User Info
      run: |
        git config --global user.email otiai10+ayanel-ci@gmail.com
        git config --global user.name "Ayanel CI"

    - name: Should Deploy?
      run: source ./scripts/should_deliver_dev.sh
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: npm run build
      if: ${{ env.SHOULD_DELIVER_DEV }}

    - name: Pack ZIP
      run: npm run pack
      if: ${{ env.SHOULD_DELIVER_DEV }}

    - name: Create Release
      if: ${{ env.SHOULD_DELIVER_DEV }}
      id: create-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.NEW_TAG }}
        release_name: ${{ env.NEW_TAG }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      if: ${{ env.SHOULD_DELIVER_DEV }}
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./release/kcwidget.zip
        asset_name: kcwidget.zip
        asset_content_type: application/zip

    - name: Publish to Chrome Web Store
      run: npm run publish
      if: ${{ env.SHOULD_DELIVER_DEV }}
      env:
        GOOGLEAPI_CLIENT_ID: ${{ secrets.GOOGLEAPI_CLIENT_ID }}
        GOOGLEAPI_CLIENT_SECRET: ${{ secrets.GOOGLEAPI_CLIENT_SECRET }}
        GOOGLEAPI_REFRESH_TOKEN: ${{ secrets.GOOGLEAPI_REFRESH_TOKEN }}

    - name: Create release announcement
      run: npm run announce
      if: ${{ env.SHOULD_DELIVER_DEV }}

    # SHOULD_DELIVER_DEV に関わらず、announcement.txtの内容をツイートする
    - name: Tweet announcement
      run: |
        announcement=`cat announcement.txt`
        npm run tweet "${announcement}"
      env:
        TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        TWITTER_ACCESS_TOKEN_KEY: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
